name: Deploy Database Migrations

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/migrations/**'
      - '.github/workflows/deploy-migrations.yml'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    outputs:
      has-migrations: ${{ steps.check.outputs.has-migrations }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for migration changes
        id: check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "backend/migrations/" || git diff --name-only HEAD~1 HEAD | grep -q ".github/workflows/deploy-migrations.yml"; then
            echo "has-migrations=true" >> $GITHUB_OUTPUT
            echo "🔍 Migration changes detected"
          else
            echo "has-migrations=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No migration changes found"
          fi

  deploy-migrations:
    needs: check-migrations
    if: needs.check-migrations.outputs.has-migrations == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy to server and run migrations
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "🚀 Starting migration deployment..."

            # Переходим в папку проекта
            cd ${{ secrets.EC2_DEPLOY_PATH }}/backend

            # Получаем последние изменения
            git pull origin master

            # Устанавливаем зависимости включая dev (для knex)
            npm ci

            # Запускаем миграции
            echo "🔄 Running database migrations..."
            npm run migrate:deploy

            # Перезапускаем PM2 приложение
            pm2 restart booking-backend || echo "PM2 restart failed, but continuing..."

            echo "✅ Migration deployment completed!"